config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'

  resources :matchusers
  resources :listings
  resources :posts do
    resources :comments
  end
  resources :users
  resources :drafts
  resources :session
  resources :faqs
  resources :comments
  resources :admins do
    resources :drafts
    resources :posts
    resources :faqs
  end

  resources :drafts do
    resources :images
  end

  get '/aboutus' => 'home#show'
  get '/FAQ' => 'about#show'
  get '/admin' => 'admins#index'
  get '/search' => 'posts#index'
  get '/admin/login' => 'session#new'
  post '/session' => 'session#create'
  delete '/session' => 'session#destroy'

end

app/views/admins/index.html.erb
<div class="section">
<div id="heading">DRAFTS</div>
<% @drafts.each do |post| %>
  <div class="row">
    <div class="post_title col-md-3"><%=raw post.title.html_safe %></div>
    <div class="post_date col-md-2"><%= post.date %></div>
    <div class="post_category col-md-2"><%= post.category %></div>
    <div class="edit_link col-md-1"><%= link_to "EDIT", edit_draft_path(post.id, :type => "save") %></div>
    <div class="delete_link col-md-1"><%= link_to "DELETE", draft_path(post.id), :method => 'delete' %></div>
    <div class="publish_link col-md-1"><%= link_to "PUBLISH", edit_draft_path(post.id, :type => "publish") %></div>
  </div>
<% end %>
</div>
<div class="section">
<div id="heading">LIVE POSTS</div>
  <% @posts.each do |post| %>
    <div class="row">
      <div class="post_title col-md-3"><%=raw post.title.html_safe %></div>
      <div class="post_date col-md-2"><%= post.date %></div>
      <div class="post_category col-md-2"><%= post.category %></div>
      <div class="edit_link col-md-1"><%= link_to "EDIT", edit_post_path(post.id) %></div>
      <div class="delete_link col-md-1"><%= link_to "DELETE", post_path(post.id), :method => 'delete' %></div>
    </div>
  <% end %>
</div>
<div class="section">
<div id="heading">LIVE FAQ</div>
  <% @faqs.each do |post| %>
    <div class="row">
      <div class="faq_question col-md-7"><%= post.question %></div>
      <div class="edit_link col-md-1"><%= link_to "EDIT", edit_faq_path(post.id) %></div>
      <div class="delete_link col-md-1"><%= link_to "DELETE", faq_path(post.id), :method => 'delete' %></div>
    </div>
  <% end %>
</div>
<div class="section">
<div id="heading">USERS</div>
  <% @users.each do |user| %>
    <div class="row">
      <div class="username col-md-4"><%= user.name %></div>
      <div class="user_email col-md-3"><%= user.email %></div>
    </div>
  <% end %>
</div>