config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'

  resources :matchusers
  resources :listings
  resources :posts do
    resources :comments
  end
  resources :users
  resources :drafts
  resources :session
  resources :faqs
  resources :comments
  resources :admins do
    resources :drafts
    resources :posts
    resources :faqs
  end

  resources :drafts do
    resources :images
  end

  get '/aboutus' => 'home#show'
  get '/FAQ' => 'about#show'
  get '/admin' => 'admins#index'
  get '/search' => 'posts#index'
  get '/admin/login' => 'session#new'
  post '/session' => 'session#create'
  delete '/session' => 'session#destroy'

end

app/models/matchuser.rb
class Matchuser < ActiveRecord::Base
  def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |product|
      csv << product.attributes.values_at(*column_names)
    end
  end
end
end

app/controllers/matchusers_controller.rb
class MatchusersController < ApplicationController

  def index

    if params["format"] == "csv"
      @matchusers = Matchuser.order(:name)
      respond_to do |format|
        format.html
        format.csv { send_data @matchusers.to_csv }
      end
    else
      render :layout => 'match'
    end
  end


  def new
    @matchuser = Matchuser.new
    render :layout => 'match'
  end

  def create
    @matchuser = Matchuser.create(matchuser_params)
    if @matchuser.save
      # Deliver the signup email
      # UserNotifier.send_match_email(@matchuser).deliver
      redirect_to matchusers_path
    else
      render :action => 'new'
    end

  end

  private
    def matchuser_params
      params.require(:matchuser).permit(:name, :email, :specialty, :phone)
    end
end

app/views/matchusers/index.html.erb
<div id="matchContainer">
<div id="header">
  <div id="titleMatch">SIGN IN</div>
</div>
    <div id=SigninButton>
      <%= link_to "SIGN IN", new_matchuser_path %>
    </div>
  </div>

app/views/matchusers/new.html.erb
<div id="matchContainer">
<div id="header">
  <div id="titleMatch">MATCH SIGN UP</div>
</div>


<div id="matchuser">
  <div id="body">
  <div class="container4 quarter mobile">
    <div id="formMatch">
      <%= form_for @matchuser do |f| %>
           <%= f.label :name %>
           </br>
           <%= f.text_field :name %>
         </br>
           <%= f.label :email %>
           </br>
           <%= f.email_field :email %>
           </br>
           <%= f.label :specialty %>
           </br>
           <%= f.text_field :specialty %>
            </br>
            <%= f.label :phone %>
            </br>
            <%= f.text_field :phone %>
             </br>
            <%= f.submit "Send" %>
          <% end %>
    </div>
  </div>
  </div>
  </div>
  </div>