config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'

  resources :matchusers
  resources :listings
  resources :posts do
    resources :comments
  end
  resources :users
  resources :drafts
  resources :session
  resources :faqs
  resources :comments
  resources :admins do
    resources :drafts
    resources :posts
    resources :faqs
  end

  resources :drafts do
    resources :images
  end

  get '/aboutus' => 'home#show'
  get '/FAQ' => 'about#show'
  get '/admin' => 'admins#index'
  get '/search' => 'posts#index'
  get '/admin/login' => 'session#new'
  post '/session' => 'session#create'
  delete '/session' => 'session#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
has_many :comments

  def self.text_search(query)
    if query.present?
      where("title @@ :q or content @@ :q or teaser @@ :q", q: query)
    else
      scoped
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

# def feed
#     @title = "The Daily Rec"
#     @posts = Post.all.order("created_at DESC")
#     @updated = @posts.first.updated_at unless @posts.empty?
#     respond_to do |format|
#       format.atom { render layout: false }
#       # we want the RSS feed to redirect permanently to the ATOM feed
#     format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
#     end
# end

def index
    if params["type"] == "all"
        @posts = Post.all.order("created_at DESC")
        @count = params["count"].to_i
        response = HTTParty.get('https://api.instagram.com/v1/users/self/media/recent/?access_token=1678934706.7497432.f3048715df0940b69ed625db492c45f5')
        @response = response["data"]
        @images = []
        @counter = 1
        @response.each do |image|
          if @counter <= 5
          imageURL = image["images"]["standard_resolution"]["url"]
          @images.push(imageURL)
        end
        @counter += 1
      end
    elsif params["type"] == "favorites"
      @posts = Post.where(category: "favorites").order("created_at DESC")
      @count = params["count"].to_i
      response = HTTParty.get('https://api.instagram.com/v1/users/self/media/recent/?access_token=1678934706.7497432.f3048715df0940b69ed625db492c45f5')
      @response = response["data"]
      @images = []
      @counter = 1
      @response.each do |image|
        if @counter <= 5
        imageURL = image["images"]["standard_resolution"]["url"]
        @images.push(imageURL)
      end
      @counter += 1
    end
  elsif params["type"] == "home"
      @posts = Post.where(category: "home").order("created_at DESC")
      @count = params["count"].to_i
      response = HTTParty.get('https://api.instagram.com/v1/users/self/media/recent/?access_token=1678934706.7497432.f3048715df0940b69ed625db492c45f5')
      @response = response["data"]
      @images = []
      @counter = 1
      @response.each do |image|
        if @counter <= 5
        imageURL = image["images"]["standard_resolution"]["url"]
        @images.push(imageURL)
      end
      @counter += 1
    end
  elsif params["type"] == "stories"
        @posts = Post.where(category: "stories").order("created_at DESC")
        @count = params["count"].to_i
        response = HTTParty.get('https://api.instagram.com/v1/users/self/media/recent/?access_token=1678934706.7497432.f3048715df0940b69ed625db492c45f5')
        @response = response["data"]
        @images = []
        @counter = 1
        @response.each do |image|
          if @counter <= 5
          imageURL = image["images"]["standard_resolution"]["url"]
          @images.push(imageURL)
        end
        @counter += 1
      end
    elsif params["search"]
        @posts = Post.text_search(params["search"])
        @count = params["count"].to_i
        response = HTTParty.get('https://api.instagram.com/v1/users/self/media/recent/?access_token=1678934706.7497432.f3048715df0940b69ed625db492c45f5')
        @response = response["data"]
        @images = []
        @counter = 1
        @response.each do |image|
          if @counter <= 5
          imageURL = image["images"]["standard_resolution"]["url"]
          @images.push(imageURL)
        end
        @counter += 1
      end
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comment = Comment.new
    @comments = Comment.where(post_id: params[:id]).order("created_at DESC")
    response = HTTParty.get('https://api.instagram.com/v1/users/self/media/recent/?access_token=1678934706.7497432.f3048715df0940b69ed625db492c45f5')
    @response = response["data"]
    @images = []
    @counter = 1
    @response.each do |image|
      if @counter <= 5
      imageURL = image["images"]["standard_resolution"]["url"]
      @images.push(imageURL)
    end
    @counter += 1
  end
  end

  def edit
    if session[:admin_id]
      @post = Post.find_by(id: params[:id])
      render :layout => 'admins'
    else
      redirect_to '/admin/login'
    end
  end

  def update
    if session[:admin_id]
      post = Post.find_by(id: params[:id])
      post.update(post_params)
      post.save
      redirect_to '/admin'
    else
      redirect_to '/admin/login'
    end
  end

  def destroy
    if session[:admin_id]
      post = Post.find_by(id: params[:id])
      post.destroy
      redirect_to '/admin'
    else
      redirect_to '/admin/login'
    end
  end

  def new
    if session[:admin_id]
      @post = Post.new
      render :layout => 'admins'
    else
      redirect_to '/admin/login'
    end
  end

  def create
    if session[:admin_id]
      @post = Post.create(post_params)
      redirect_to '/admin'
    else
      redirect_to '/admin/login'
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :date, :teaser, :content, :admin_id, :pictures, :category, :layout)
    end
end

app/views/posts/edit.html.erb
<!-- <div id="urlField" class="form">
	Link Address: </br><input id="url"></input>
	<button class="btn" id="urlButton">+</button>
</div> -->

<div id="form1">
  <%= form_for @post do |f| %>

           <div class="section">
              <%= f.label :title %>
              </br>
              <%= f.text_field :title %>
            </div>

           <div class="section">
              <%= f.label :date %>
              </br>
              <%= f.text_field :date %>
           </div>

           <div class="section">
              <%= f.label :teaser %>
              </br>
              <%= f.text_area :teaser, id: "teaser" %>
           </div>
           <div class="section">
              <%= f.label :content %>
              </br>
              <%= f.text_area :content, id: "content" %>
           </div>

           <div class="section">
              <%= f.label :pictures %>
              </br>
              <%= f.text_field :pictures, as: :array %>
              <%= f.hidden_field :admin_id, :value => session[:admin_id] %>
           </div>

           <div class="section">
             <div class="category">
               <%= f.radio_button :category, 'favorites', :checked => true %>
               <%= f.label :category_favorites, 'Current Favorites' %>
             </div>
             <div class="category">
               <%= f.radio_button :category, 'stories' %>
               <%= f.label :category_stories, 'Stories' %>
             </div>
             <div class="category">
               <%= f.radio_button :category, 'home' %>
               <%= f.label :category_home, 'At Home' %>
             </div>
           </div>

           <div class="section">
           <div id="layoutHolder">
            <div class="radioHolder">
              <div class="buttonHolder">
              <%= f.radio_button :layout, 'pictureLeft', :checked => true %>
              <%= f.label :layout_pictureLeft, 'Picture on Left', :class => "layoutTitle"  %>
              </div>
              <%= image_tag 'PictureLeft.png'%>
            </div>
            <div class="radioHolder">
              <div class="buttonHolder">
              <%= f.radio_button :layout, 'horizontalPicture' %>
              <%= f.label :layout_horizontalPicture, 'Picture Horizontal', :class => "layoutTitle"  %>
              </div>
              <%= image_tag 'horizontalTop.png'%>
             </div>
             <div class="radioHolder">
               <div class="buttonHolder">
              <%= f.radio_button :layout, 'threePics' %>
              <%= f.label :layout_threePics, '3 Pictures On Top', :class => "layoutTitle"  %>
              </div>
              <%= image_tag 'threeonTop.png'%>
             </div>
             <div class="radioHolder">
               <div class="buttonHolder">
              <%= f.radio_button :layout, 'pictureRight' %>
              <%= f.label :layout_pictureRight, 'Picture on Right', :class => "layoutTitle" %>
              </div>
              <%= image_tag 'PictureRight.png'%>
            </div>
          </div>
        </div>
   <div id="formButtonHolder">
     <%= f.submit "SAVE" %>
      <% end %>
      </div>
</div>

<script>
			$('#content').wysihtml5({
        "html": true
			});
</script>
<script>
      $('#teaser').wysihtml5({
        "html": true
			});
</script>
<script>
      $('#title').wysihtml5({
        "html": true
			});

		</script>

app/views/posts/index.html.erb
<!-- <% if params["type"] == "favorites" %>
  <div id="header">
    <div id="title1">Current Favorites</div>
  </div>
<% elsif params["type"] == "stories" %>
  <div id="header">
    <div id="title1">Stories</div>
  </div>
<% elsif params["type"] == "home" %>
  <div id="header">
    <div id="title1">At Home</div>
  </div>
<% elsif params["search"].present? %>
  <div id="header">
    <div id="title1">Search Results</div>
  </div>
<% end %> -->

<div id="buffer"></div>

<% if @posts.empty? %>
  <% if params["search"].present? %>
    <div id="listings">No results came up for your search</div>
  <% else %>
    <div id="listings">There are no posts for this blog yet!</div>
  <% end %>
<% end %>
<% @start = 0 + @count %>
<% @counter = 4 + @count %>
<% @posts[@start..@counter].each do |post| %>


  <% if post.layout == "pictureLeft" %>
    <div id="layout1" class="post">
        <div id="left" class="layout1">
          <div id="leftImage" class="layout1">
            <img class="postImage" src="<%= post.pictures[0] %>">
          </div>
        </div>
        <div id="right" class="layout1">
          <div id="postTitle1" class="layout1 info"><%=raw post.title.html_safe %></div>
          <div id="postDate1" class="layout1 info"><%= post.date%></div>
          <div id="postBlurb1" class="layout1 info"><%=raw post.teaser.html_safe %></div>
          <div id="postButton1" class="blogButton"><%= link_to "Show More", post_path(post.id) %></div>
        </div>
    </div>
  <% elsif post.layout == "horizontalPicture"%>
    <div id="layout2" class="post">
      <div id="top2" class="layout2">
        <img class="postImage" class="postImage" src="<%= post.pictures[0] %>">
      </div>
      <div id="bottom" class="layout2">
        <div id="bottomLeft" class="layout2">
          <div id="postBlurb2" class="layout2 info"><%=raw post.teaser.html_safe %></div>
        </div>
        <div id="bottomRight" class="layout2">
          <div id="postTitle2" class="layout2 info"><%=raw post.title.html_safe %></div>
          <div id="postDate2" class="layout2 info"><%= post.date%></div>
          <div id="postButton1" class="blogButton"><%= link_to "Show More", post_path(post.id) %></div>
        </div>
      </div>
    </div>
  <% elsif post.layout == "threePics" %>
  <div id="layout3" class="post">
    <div id="top" class="layout3">
      <img id="pic1" src="<%= post.pictures[0] %>">
      <img id="pic2" src="<%= post.pictures[1] %>">
      <img id="pic3" src="<%= post.pictures[2] %>">
    </div>
    <div id="bottom" class="layout2">
      <div id="bottomLeft" class="layout2">
        <div id="postBlurb2" class="layout2 info"><%=raw post.teaser.html_safe %></div>
      </div>
      <div id="bottomRight" class="layout2">
        <div id="postTitle2" class="layout2 info"><%=raw post.title.html_safe %></div>
        <div id="postDate2" class="layout2 info"><%= post.date%></div>
        <div id="postButton1" class="blogButton"><%= link_to "Show More", post_path(post.id) %></div>
      </div>
    </div>
  </div>
  <% elsif post.layout == "pictureRight" %>
    <div id="layout4" class="post">
        <div id="left" class="layout4">
          <div id="postTitle1" class="layout4 info"><%=raw post.title.html_safe %></div>
          <div id="postDate1" class="layout4 info"><%= post.date%></div>
          <div id="postBlurb1" class="layout4 info"><%=raw post.teaser.html_safe %></div>
          <div id="postButton4" class="blogButton"><%= link_to "Show More", post_path(post.id) %></div>
        </div>
        <div id="right" class="layout4">
          <div id="leftImage" class="layout1">
            <img class="postImage" src="<%= post.pictures[0] %>"/>
          </div>
        </div>
    </div>
  <% end %>
<% end %>
<% @newCounterMore = @counter + 1 %>
<% @newCounterLess = @start - 5 %>

<% if @posts.length < 5 %>

<script type="text/javascript">
$(document).ready(function(){
  $('#moreLess').css("display","none");
  console.log("erased")
})
</script>
<% end %>

<div id="moreLess">
<% if @newCounterMore < @posts.length %>
  <div id="older" class=".blogButton">
  <%= link_to "SEE OLDER POSTS", :type => params["type"], :count => @newCounterMore  %>
  </div>
<% end %>
<% if @start > 0 %>
  <div id="newer" class=".blogButton">
  <%= link_to "SEE NEWER POSTS", :type => params["type"], :count => @newCounterLess  %>
  </div>
<% end %>
</div>



  <div class="wrap mobile">
    <div class="instaTitle2 mobile">INSTAGRAM </div>
    <div class="instaTitle3 mobile"><a href="http://www.instagram.com/thedailyrec">@THEDAILYREC</a></div>
    <div class="instaHolder2 mobile">
      <% @images.each do |image| %>
      <div class="insta2 mobile">
        <img src="<%= image %>" data-pin-hover="true">
      </div>
      <% end %>
    </div>
    </div>

app/views/posts/new.html.erb
<!-- <div id="urlField" class="form">
	Link Address: </br><input id="url"></input>
	<button class="btn" id="urlButton">+</button>
</div> -->

<div id="form1">
  <%= form_for @post do |f| %>

           <div class="section">
              <%= f.label :title %>
              </br>
              <%= f.text_field :title %>
            </div>

           <div class="section">
              <%= f.label :date %>
              </br>
              <%= f.text_field :date %>
           </div>

           <div class="section">
              <%= f.label :teaser %>
              </br>
              <%= f.text_area :teaser, id: "teaser" %>
           </div>
           <div class="section">
              <%= f.label :content %>
              </br>
              <%= f.text_area :content, id: "content" %>
           </div>

           <div class="section">
              <%= f.label :pictures %>
              </br>
              <%= f.text_field :pictures, as: :array %>
              <%= f.hidden_field :admin_id, :value => session[:admin_id] %>
           </div>

           <div class="section">
             <div class="category">
               <%= f.radio_button :category, 'favorites', :checked => true %>
               <%= f.label :category_favorites, 'Current Favorites' %>
             </div>
             <div class="category">
               <%= f.radio_button :category, 'stories' %>
               <%= f.label :category_stories, 'Stories' %>
             </div>
             <div class="category">
               <%= f.radio_button :category, 'home' %>
               <%= f.label :category_home, 'At Home' %>
             </div>
           </div>

           <div class="section">
           <div id="layoutHolder">
            <div class="radioHolder">
              <div class="buttonHolder">
              <%= f.radio_button :layout, 'pictureLeft', :checked => true %>
              <%= f.label :layout_pictureLeft, 'Picture on Left', :class => "layoutTitle"  %>
              </div>
              <%= image_tag 'PictureLeft.png'%>
            </div>
            <div class="radioHolder">
              <div class="buttonHolder">
              <%= f.radio_button :layout, 'horizontalPicture' %>
              <%= f.label :layout_horizontalPicture, 'Picture Horizontal', :class => "layoutTitle"  %>
              </div>
              <%= image_tag 'horizontalTop.png'%>
             </div>
             <div class="radioHolder">
               <div class="buttonHolder">
              <%= f.radio_button :layout, 'threePics' %>
              <%= f.label :layout_threePics, '3 Pictures On Top', :class => "layoutTitle"  %>
              </div>
              <%= image_tag 'threeonTop.png'%>
             </div>
             <div class="radioHolder">
               <div class="buttonHolder">
              <%= f.radio_button :layout, 'pictureRight' %>
              <%= f.label :layout_pictureRight, 'Picture on Right', :class => "layoutTitle" %>
              </div>
              <%= image_tag 'PictureRight.png'%>
            </div>
          </div>
        </div>
   <div id="formButtonHolder">
      <%= f.submit "Send" %>
    </div>
      <% end %>

      <script>
      			$('#content').wysihtml5({
              "html": true
      			});
      </script>
      <script>
            $('#teaser').wysihtml5({
              "html": true
      			});
      </script>
      <script>
            $('#title').wysihtml5({
              "html": true
      			});

      		</script>

app/views/posts/show.html.erb
<div id="postHolder">
    <div id="topImage">
      <img src="<%= @post.pictures[0] %>" id="top_img">
    </div>
    <div id="contentArea">
      <div id="showTitle"><%=raw @post.title.html_safe %></div>
    </div>
    <div id="contentArea">
      <% @admin = Admin.find_by(id: @post.admin_id)%>
      <div id="showDateCategory"><%= @post.date %> // <%= @admin.name if @admin.present? %></div>
    </div>
    <div id="contentArea">
      <div id="showContent"><%=raw @post.content.html_safe %></div>
    </div>
    <% @post.pictures.each do |picture| %>
      <% if @post.pictures.index(picture) == 0 %>
      <% else %>
        <div id="topImage">
          <img src="<%= picture %>">
        </div>
      <% end %>
    <% end %>
    <div id="bottomBuffer">
    </div>
</div>

<div class="comment mobile">
  <div id="comment">COMMENTS
    <% if @comments.length != 0 %>
    (<%= @comments.length %>)
    <% end %>
    </div>
  <div id="comment"><%= image_tag 'arrowDown.png', :id => "arrow" %><%= image_tag 'arrowUp.png', :id => "arrow", :style => "display: none"%></div>
  <%= form_for [@post,@comment] do |f| %>
    <%= f.label :name %>: <%= f.text_field :name %>
    <%= f.label :message %>: <%= f.text_field :message %>
    <%= f.hidden_field :post_id, :value => params[:id] %>
  <%= f.submit "Send", :id => "commentSubmit" %>
<% end %>
</div>

<div id="comments">
<% @comments.each do |comment| %>
  <div class="comments"><%= comment.name %>: <%= comment.message %> <%= link_to image_tag('heart.png'), edit_post_comment_path(@post.id,comment.id) %><%= comment.likes %></div>
<% end %>
</div>

<div class="wrap mobile">
  <div class="instaTitle2 mobile">INSTAGRAM </div>
  <div class="instaTitle3 mobile"><a href="http://www.instagram.com/thedailyrec">@THEDAILYREC</a></div>
  <div class="instaHolder2 mobile">
    <% @images.each do |image| %>
    <div class="insta2 mobile">
      <img src="<%= image %>">
    </div>
    <% end %>
  </div>
  </div>